---
title: "VVG_product_results"
author: "Joe Hilgard"
date: "January 18, 2016"
output: 
  word_document:
    reference_docx: template_0.docx
---

```{r setup, echo = F, include = F}
source("1-analysis.R")
# function for printing p-values
printp = function(x) {
  if (x > 1) return("That ain't a p-value, buddy!")
  if (x == 1) return("*p* = 1.000")
  if (x < .001) return("*p* < .001")
  if (x >= .001 & x < 1) return(paste("*p* = ", substring(x, 2), sep = ""))  
}
# function for printing b, t, p
fetch_stats = function(x, df) {
  paste("*b* = ", x[1], ", *t*(", df, ") = ", x[3], ", ", printp(x[4]), sep="")
}
# function for printing M and SD
m_sd = function(x) {
  paste0("*M* = ", round(mean(x, na.rm=T),2), 
        ", *SD* = ", round(sd(x, na.rm=T),2)
        )
}
```


**Manipulation check.** We tested how assignment to the 2 × 2 design influenced participants’ in-game performance, as measured by the number of times the player died and the number of monsters the player killed. Count of player deaths was Poisson-distributed. Participants in the powerful-gun condition died significantly fewer times than those in the weak-gun condition `r fetch_stats(coef.deaths["Power_f"], df.deaths)`*(b = -.376, SEb = .129, p = .004)*, while the type of gun (realistic vs. sci-fi) did not significantly influence this outcome `r fetch_stats(coef.deaths["Gun_type_f"], df.deaths)`*(b = .028, SEb = .046, p = .539)*, nor did gun type and gun power significantly interact `r fetch_stats(coef.deaths["Power_f:Gun_type_f"], df.deaths)`*(b = .017, SEb = .046, p = .715)*.  Similarly, participants in the powerful-gun condition killed substantially more enemies than did those in the weak-gun condition, `r fetch_stats(coef.kills["Power_f"], df.kills)`. Unexpected effects of gun type and a gun type × power interaction were detected such that participants in the AR-15 condition killed fewer monsters than their ZQ-5 counterparts (main effect: `r fetch_stats(coef.kills["Gun_type_f"], df.kills)`) particularly when the AR-15 was powerful the powerful-gun condition (interaction effect: `r fetch_stats(coef.kills["Gun_type_f:Power_f"], df.kills)`. 

Regrettably, we did not ask participants directly about how fun, powerful, satisfying, etc. the in-game gun was. As such, we do not have direct evidence that the powerful gun was more pleasant to use than the weak gun, although we might infer that from the observed difference in efficacy. 

Means and SDs of all variables are summarized in Table 2. Combination violin/boxplots for each outcome are summarized in Figure 2.

**2nd Amendment Advocacy.** Participants’ 2nd Amendment advocacy was best modeled by a simple additive model of political orientation and gender (BF = `r exp(mod1_cov["pol_orien_f + Gender_f"]@bayesFactor$bf) %>% signif(3)` : 1). Adding the main and interactive effects of gun type and gun power to this model was not preferred. The covariates-only model was preferred to the full model, BF = 1 : `r (exp(mod1_cov["pol_orien_f + Gender_f"]@bayesFactor$bf)/exp(mod1_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`. The addition of the interaction was not supported `r (exp(mod1_cov["Gun_type_f + Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)/exp(mod1_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`  

**Product attitudes.** Again, attitudes towards the AR-15 were best described by a simple additive model of political orientation and gender, BF = `r exp(mod2_cov["pol_orien_f + Gender_f"]@bayesFactor$bf) %>% signif(3)`. The covariates-only model was preferred to the full model, BF = 1 : `r (exp(mod2_cov["pol_orien_f + Gender_f"]@bayesFactor$bf)/exp(mod2_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`. The addition of the interaction was not supported `r (exp(mod2_cov["Gun_type_f + Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)/exp(mod2_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`  

**Purchasing intentions.** Purchasing intentions were right-skewed. However, the QQplot of standardized residuals was not unbearably ugly, and transformation by square root or logarithm did not make them prettier. Thus, we present this outcome in its natural units. 

Purchasing intentions were best described by additive effects of political orientation and gender, BF = `r exp(mod3_cov["pol_orien_f + Gender_f"]@bayesFactor$bf) %>% signif(3)`. The covariates-only model was preferred to the full model, BF = 1 : `r (exp(mod3_cov["pol_orien_f + Gender_f"]@bayesFactor$bf)/exp(mod3_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`. The addition of the interaction was not supported `r (exp(mod3_cov["Gun_type_f + Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)/exp(mod3_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`  

**Desire of in-game weapon.** This variable was very badly right-skewed, with most participants choosing the minimum response. Square-root or log transformation did little to fix this. We report this in its natural units, but readers with better ideas for modeling are encouraged to use the raw data.

Weapon desire was best described by an effect of gender, BF = `r exp(mod4_cov["Gender_f"]@bayesFactor$bf) %>% signif(3)`. The covariates-only model was preferred to the full model, BF = 1 : `r (exp(mod4_cov["Gender_f"]@bayesFactor$bf)/exp(mod4_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`. The addition of the interaction was not supported `r (exp(mod4_cov["Gun_type_f + Power_f + Gender_f"]@bayesFactor$bf)/exp(mod4_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + Gender_f"]@bayesFactor$bf)) %>% signif(3)`  

**Policy opinion.** Policy views were best modeled by political orientation alone. Gender did not seem to predict policy views over and above political orientation (BF ~4). The experimental condition didn’t do squat.

Policy views were best described by political orientation alone, BF = `r exp(mod5_cov["pol_orien_f"]@bayesFactor$bf) %>% signif(3)`. This covariate-only model was preferred to the full model, BF = 1 : `r (exp(mod5_cov["pol_orien_f"]@bayesFactor$bf)/exp(mod5_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f"]@bayesFactor$bf)) %>% signif(3)`. The addition of the interaction was not supported `r (exp(mod5_cov["Gun_type_f + Power_f + pol_orien_f"]@bayesFactor$bf)/exp(mod5_cov["Gun_type_f + Power_f + Gun_type_f:Power_f + pol_orien_f"]@bayesFactor$bf)) %>% signif(3)`  

**Rates of gun accidents and gun use.** Participants’ estimated rates seemed to be more appropriately modeled as a gamma distribution than a normal distribution. Because responses of 0% cannot be modeled under this distribution, these responses were adjusted to 0.001%. In general, we note that estimates contained considerable uncertainty and noise, with estimates ranging from 0% to 80% or more.

Only a few idiosyncratic predictors reached statistical significance. Republicans, relative to liberals, thought it more probable that a gun owner would experience a gun-related accident such as an accidental discharge. Men, relative to women, thought it more probable that a gun owner might have a gun stolen from them. Libertarians, relative to other political parties, thought it more probable that a gun owner would ever use their gun in an act of self-defense. None of these estimated rates were significantly predicted by the game participants had played.

**[INSERT TABLE OF MODEL OUTPUT HERE]**

**Magazine capacity.** Several participants listed very large values (e.g., 100 or more) for a maximum magazine size, or wrote in responses to the effect that there should be no such government-imposed limit. We tried modeling this outcome in two ways. First, we winsorized all responses in excess of 30 down to 30 and attempted a linear model. Second, we coded a dichotomous variable for responses less than 30 and responses equal to or greater than 30 and attempted a logistic model. Neither model revealed any significant effects of game.

**[INSERT TWO TABLES OF MODEL OUTPUT HERE]**


